INSERT INTO clientes (nome, plano) VALUES
('ADILSON', 'Mensal'),
('ALBERTO', 'Mensal'),
('ALIXSON', 'Mensal'),
('ANDERSON', 'Nenhum'),
('ANDRÉ', 'Nenhum'),
('ANTONIO', 'Nenhum'),
('BARBOSA', 'Nenhum'),
('BERG', 'Nenhum'),
('BRUNO LINS', 'Nenhum'),
('CAIO SOBRINHO DE ZENILDO', 'Nenhum'),
('CARLOS', 'Mensal'),
('DANIEL FARIAS', 'Mensal'),
('DAVI DE WAGNER', 'Nenhum'),
('DAVI PIRES', 'Mensal'),
('DAVI SARINHO', 'Mensal'),
('EDRÍSIO', 'Mensal'),
('Eduardo', 'Nenhum'),
('ELIAS', 'Nenhum'),
('EPITÁCIO', 'Nenhum'),
('EVANDER', 'Nenhum'),
('EZEQUIEL NARA', 'Nenhum'),
('FELIPE FOFINHO', 'Nenhum'),
('FLAVIO DE PAULO', 'Nenhum'),
('HUGO PRF', 'Nenhum'),
('INGLISON', 'Nenhum'),
('ISMAEL JORGE', 'Mensal'),
('JADSON LUAN', 'Mensal'),
('JEFERSON', 'Nenhum'),
('JOALISON MOREIRA', 'Nenhum'),
('JOBSON', 'Mensal'),
('JOELTON', 'Nenhum'),
('JOHN E PEDRO', 'Nenhum'),
('JOSÉ PEDRO', 'Nenhum'),
('JUAN', 'Nenhum'),
('JUNIOR MUIDEZES', 'Nenhum'),
('KELVIN', 'Mensal'),
('KEMUEL', 'Nenhum'),
('LINS', 'Nenhum'),
('LUAN', 'Nenhum'),
('LUCAS VINICIUS', 'Nenhum'),
('LUCCA', 'Mensal'),
('LUIZ PM', 'Nenhum'),
('LUIZINHO', 'Nenhum'),
('MÁRCIO FOTÓGRAFO', 'Nenhum'),
('MARIA IRMÃO DE MATEUS', 'Nenhum'),
('MARLEN CETEPA', 'Nenhum'),
('MATHEUS ALEXANDRE', 'Nenhum'),
('MATHEUS ALMEIDA', 'Mensal'),
('MAURO', 'Nenhum'),
('MIKAEL', 'Nenhum'),
('MOISÉS', 'Nenhum'),
('NANDO', 'Nenhum'),
('NATAN FRANÇA', 'Nenhum'),
('NATNAN JOEL', 'Mensal'),
('NELSON', 'Nenhum'),
('NETINHO FEIRA', 'Nenhum'),
('NETO', 'Mensal'),
('NETO DE FÁTIMA VIZINHA', 'Nenhum'),
('NIKOLAS', 'Nenhum'),
('PEDRINHO', 'Nenhum'),
('PEDRO BLACK', 'Nenhum'),
('PEDRO HENRIQUE', 'Nenhum'),
('RAFAEL GREENVILE', 'Nenhum'),
('RAMON AMIGO DE LUKINHA', 'Nenhum'),
('RHUAN', 'Nenhum'),
('RICARDO BOTICARIO', 'Nenhum'),
('RINALDO', 'Mensal'),
('RODRIGO MELO', 'Nenhum'),
('RODRIGO PELADA', 'Nenhum'),
('SR. EDVALDO', 'Mensal'),
('THAMYRES', 'Nenhum'),
('THIAGO BARBOSA', 'Nenhum'),
('THIAGO FERREIRA', 'Nenhum'),
('THIAGO GREENVILE', 'Nenhum'),
('TIA NESON', 'Nenhum'),
('TOMAZ', 'Mensal'),
('VALCÉLIO', 'Nenhum'),
('VINICIUS', 'Nenhum'),
('WAGNER PELADA', 'Mensal'),
('WAGNER SOUZA', 'Nenhum'),
('WERNECK', 'Nenhum'),
('WILLAMS COSTA', 'Nenhum'),
('WILLINELSON', 'Nenhum'),
('WLLER', 'Nenhum'),
('ZE VITOR', 'Nenhum'),
('ZENILDO', 'Nenhum');